### PR TITLE
Add Polish locale

### PR DESCRIPTION
**Pull request by jakubkaczor**

### CODE REVIEW

**Comment by jakubkaczor** [comment]
In Polish typography, leaving one-letter word at the end of a line is considered an error. <https://pl.wikipedia.org/wiki/Sierotka_(typografia)> Polish locale introduces one-letter “i” as the list separator. It needs to be dealt accordingly, but—in my opinion—is outside the scope of this pull request.

**Comment by josephwright** [comment]
Looks good but could you add to the ChangeLog and to the documentation?

**Comment by josephwright** [comment]
Also please add something to the locale test file.

**Comment by josephwright** [comment]
I agree about the end-of-line stuff being out-of-scope.

**Comment by jakubkaczor** [comment]
Ok. Is it good, now?

**Comment by josephwright** [comment]
Closer - but please don't edit the `v2` files as they are frozen

**Comment by jakubkaczor** [comment]
Ok. I restored *v2* files.

**Pull request merged**
